In [5]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [9]:
#URL = "https://www.worldometers.info/coronavirus/#countries"
html_page = requests.get("https://www.worldometers.info/coronavirus/#countries").text
soup = BeautifulSoup(html_page,'lxml')

In [10]:
get_table = soup.find("table",id="main_table_countries_today")

In [11]:
get_table_data = get_table.tbody.find_all("tr")
get_table_data

[<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>3,560,801</td>
 <td>+4,907</td>
 <td>176,618</td>
 <td>+480</td>
 <td>1,611,039</td>
 <td>+4,060</td>
 <td>1,773,144</td>
 <td>18,382</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>2,550,729</td>
 <td>+1,212</td>
 <td>94,967</td>
 <td>+42</td>
 <td>1,566,877</td>
 <td>+262</td>
 <td>888,885</td>
 <td>13,569</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>2,630,169</td>
 <td>+52</td>
 <td>63,294</td>
 <td>+1</td>
 <td>1,778,391</td>
 <td>+76</td>
 <td>788,484</td>
 <td>19,506</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>2,492,804</td>
 <td></td>
 <td>193,989</td>
 <td></td>
 <td>1,437,425</td>
 <td></td>
 <td>861,390</td>
 <td>5,555</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>493,710</td>
 <td></td>
 <td>11,649</td>
 <td></td>
 <td>238,464</td>
 <td></td>
 <td>243,597</td>
 <td>956</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>10,235</td>
 <td>+2</td>
 <td>128</td>
 <td></td>
 <td>9,019</td>
 <td>+2</td>
 <td>1,088</td>
 <td>6</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>651</td>
 <td></td>
 <td>55</td>
 <td>4</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>11,739,169</td>
 <td>+6,173</td>
 <td>540,660</td>
 <td>+523</td>
 <td>6,641,866</td>
 <td>+4,400</td>
 <td>4,556,643</td>
 <td>57,978</td>
 <td>1,506</td>
 <td>69.4</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">3,040,833</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">132,979 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">1,324,947</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,582,907</td>
 <td style="font-weight: bold; text-align:right">15,198</td>
 <td style="font-weight: bold; text-align:right">9,186</td>
 <td style="font-weight: bold; text-align:right">402</td>
 <td style="font-weight: bold; text-align:right">38,217,640</td>
 <td style="font-weight: bold; text-align:right">115,449</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">331,034,037</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>109</td><td>2,489</td><td>9</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">1,626,071</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">65,556 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">978,615</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">581,900</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">7,649</td>
 <td style="font-weight: bold; text-align:right">308</td>
 <td style="font-weight: bold; text-align:right">3,330,562</td>
 <td style="font-weight: bold; text-align:right">15,667</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,582,910</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>131</td><td>3,243</td><td>64</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">720,346</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">20,174 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">440,150</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">260,022</td>
 <td style="font-weight: bold; text-align:right">8,944</td>
 <td style="font-weight: bold; text-align:right">522</td>
 <td style="font-weight: bold; text-align:right">15</td>
 <td style="font-weight: bold; text-align:right">9,969,662</td>
 <td style="font-weight: bold; text-align:right">7,223</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,380,196,747</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>1,916</td><td>68,415</td><td>138</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">687,862</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">10,296 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">454,329</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">223,237</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">4,713</td>
 <td style="font-weight: bold; text-align:right">71</td>
 <td style="font-weight: bold; text-align:right">21,335,394</td>
 <td style="font-weight: bold; text-align:right">146,197</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,935,642</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>212</td><td>14,174</td><td>7</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
 <td style="font-weight: bold; text-align:right">305,703</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">10,772 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">197,619</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">97,312</td>
 <td style="font-weight: bold; text-align:right">1,236</td>
 <td style="font-weight: bold; text-align:right">9,270</td>
 <td style="font-weight: bold; text-align:right">327</td>
 <td style="font-weight: bold; text-align:right">1,800,690</td>
 <td style="font-weight: bold; text-align:right">54,604</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">32,977,406</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>108</td><td>3,061</td><td>18</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
 <td style="font-weight: bold; text-align:right">298,869</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">28,388 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">617</td>
 <td style="font-weight: bold; text-align:right">6,392</td>
 <td style="font-weight: bold; text-align:right">607</td>
 <td style="font-weight: bold; text-align:right">5,734,599</td>
 <td style="font-weight: bold; text-align:right">122,652</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,755,120</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>156</td><td>1,647</td><td>8</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>
 <td style="font-weight: bold; text-align:right">298,557</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">6,384 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">264,371</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">27,802</td>
 <td style="font-weight: bold; text-align:right">2,069</td>
 <td style="font-weight: bold; text-align:right">15,616</td>
 <td style="font-weight: bold; text-align:right">334</td>
 <td style="font-weight: bold; text-align:right">1,198,261</td>
 <td style="font-weight: bold; text-align:right">62,675</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/chile-population/">19,118,631</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>64</td><td>2,995</td><td>16</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">285,768</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">44,236 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">231</td>
 <td style="font-weight: bold; text-align:right">4,209</td>
 <td style="font-weight: bold; text-align:right">652</td>
 <td style="font-weight: bold; text-align:right">10,651,308</td>
 <td style="font-weight: bold; text-align:right">156,886</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">67,891,886</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>238</td><td>1,535</td><td>6</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
 <td style="font-weight: bold; text-align:right">261,750</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,902</td>
 <td style="font-weight: bold; text-align:right;">31,119 </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+480</td>
 <td style="font-weight: bold; text-align:right">159,657</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,053</td>
 <td style="text-align:right;font-weight:bold;">70,974</td>
 <td style="font-weight: bold; text-align:right">378</td>
 <td style="font-weight: bold; text-align:right">2,030</td>
 <td style="font-weight: bold; text-align:right">241</td>
 <td style="font-weight: bold; text-align:right">641,142</td>
 <td style="font-weight: bold; text-align:right">4,972</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">128,951,496</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>493</td><td>4,144</td><td>201</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
 <td style="font-weight: bold; text-align:right">243,051</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">11,731 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">204,083</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">27,237</td>
 <td style="font-weight: bold; text-align:right">3,201</td>
 <td style="font-weight: bold; text-align:right">2,893</td>
 <td style="font-weight: bold; text-align:right">140</td>
 <td style="font-weight: bold; text-align:right">1,820,000</td>
 <td style="font-weight: bold; text-align:right">21,665</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">84,006,568</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>346</td><td>7,161</td><td>46</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">241,819</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">34,869 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">192,241</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">14,709</td>
 <td style="font-weight: bold; text-align:right">72</td>
 <td style="font-weight: bold; text-align:right">4,000</td>
 <td style="font-weight: bold; text-align:right">577</td>
 <td style="font-weight: bold; text-align:right">5,660,454</td>
 <td style="font-weight: bold; text-align:right">93,623</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,460,068</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>250</td><td>1,734</td><td>11</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/pakistan/">Pakistan</a></td>
 <td style="font-weight: bold; text-align:right">231,818</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">4,762 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">131,649</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">95,407</td>
 <td style="font-weight: bold; text-align:right">2,406</td>
 <td style="font-weight: bold; text-align:right">1,049</td>
 <td style="font-weight: bold; text-align:right">22</td>
 <td style="font-weight: bold; text-align:right">1,420,623</td>
 <td style="font-weight: bold; text-align:right">6,430</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/pakistan-population/">220,931,964</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>953</td><td>46,395</td><td>156</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saudi-arabia/">Saudi Arabia</a></td>
 <td style="font-weight: bold; text-align:right">213,716</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,968 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">149,634</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">62,114</td>
 <td style="font-weight: bold; text-align:right">2,254</td>
 <td style="font-weight: bold; text-align:right">6,138</td>
 <td style="font-weight: bold; text-align:right">57</td>
 <td style="font-weight: bold; text-align:right">1,934,391</td>
 <td style="font-weight: bold; text-align:right">55,554</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/saudi-arabia-population/">34,819,965</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>163</td><td>17,693</td><td>18</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
 <td style="font-weight: bold; text-align:right">206,844</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">5,241 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">182,995</td>
 <td style="font-weight: bold; text-align:right;"></td>

In [42]:
dic = {}
for i in range(len(get_table_data)):
  try:
     key = get_table_data[i].find_all("a",href=True)[0].string 
     #print(key)
  except:
     key = get_table_data[i].find_all("td")[0].string
    # print(key)   
values = [j.string for j in get_table_data[i].find_all('td')]
column_names =["Total Cases","New Cases","Total Deaths","New Deaths","Total Recovered","Active","Serious Critical","Tot cases/1M pop","Tot Deaths/1M pop"]
dic[key] = values
pd.DataFrame(dic).iloc[1:,:].T

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
China,China,"83,565",+8,"4,634",None,"78,528",+10,403,6,58,3,"90,410,000","62,814","1,439,323,776",Asia,"17,224","310,601",16

In [46]:
df= pd.DataFrame(dic).iloc[1:,:].T.iloc[:,:9]
df.index_name = "country"
#print(df)

In [47]:
df.columns = column_names
df.head()

,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,Active,Serious Critical,Tot cases/1M pop,Tot Deaths/1M pop
China,China,"83,565",+8,"4,634",None,"78,528",+10,403,6